set RECIPE_NAME=direct-network

set GPP_PATH="./win-gpp/gpp"
set TEXTPAR_PATH="./win-textparser/textparser.exe"
set DIRECTORY=../sdcard/pi-kitchen/%RECIPE_NAME%
set RECIPE_DIRECTORY=../recipes
set TEMPLATE_FILE=TMP_README_RECIPE_CARD.md
set THETARGETFILE=README.md
set TEMPLATE_FILE_HTML=TMP_RECIPE_CARD.html
set THETARGETFILE_HTML=%RECIPE_NAME%_RECIPE_CARD.html

%TEXTPAR_PATH% %TEMPLATE_FILE%
%GPP_PATH% -O "%DIRECTORY%/%THETARGETFILE%" output.txt -I"%DIRECTORY%"

%TEXTPAR_PATH% %TEMPLATE_FILE_HTML%
%GPP_PATH% -O "%RECIPE_DIRECTORY%/%THETARGETFILE_HTML%" output.txt -I"%DIRECTORY%"

pause